bazinga_jstranslation_js:
    pattern:  /translations/{domain}.{_format}
    defaults: { _controller: bazinga.jstranslation.controller:getTranslationsAction, domain: "messages", _format: "js" }
    methods:  [ GET ]
    options:
        i18n: false
    requirements:
        _format: js|json
        domain: "[\w]+"

bazinga_jstranslation_multiple_js:
    pattern:  /multiple_translations/{domains}.{_format}
    defaults: { _controller: bazinga.jstranslation.controller:getMultipleTranslationsAction, _format: "js" }
    methods:  [ GET ]
    options:
        i18n: false
    requirements:
        _format: js|json
        domains: "[\w,]+"